using UnityEditor;
using UnityEngine;

namespace Sapphire.EditorTools
{
    /// <summary>
    /// Configures texture importer settings for the HUD/menu art: the
    /// original REMEDIATION_PLAN.md Phase 2/3 assets (movement stick, Odin
    /// menu panel/icons/lock badge) plus the 2026-09-15 gemless
    /// MapleStory-M UI kit additions (section divider, region nameplate,
    /// primary/secondary buttons, hamburger icon, level badge). Split out of
    /// <see cref="ArtImportConfigurator"/> (that file was pushing past this
    /// codebase's ~500-line convention - same "keep files under ~500 lines"
    /// split already applied to <see cref="VillageHubUiBuilder"/>/
    /// <see cref="VillageHubSkillMenuBuilder"/>/<see cref="VillageHubMenuBuilder"/>).
    /// Reuses <see cref="ArtImportConfigurator"/>'s ConfigureMultiSprite/
    /// ConfigureSingleSprite (made internal for this purpose) rather than
    /// duplicating them.
    /// </summary>
    internal static class HudArtImportConfigurator
    {
        internal static void ConfigureAll()
        {
            ConfigureMovementStick();
            ConfigureMenuPanelOdin();
            ConfigureMenuSectionDivider();
            ConfigureRegionNameplate();
            ConfigureButtons();
            ConfigureMenuHamburgerIcon();
            ConfigureLevelBadge();
            ConfigureMenuIconsSet();
            ConfigureDarkMenuArt();
            ConfigureMenuLockBadge();
            ConfigureGaugeFillMana();
        }

        private static void ConfigureGaugeFillMana()
        {
            // UI: MP gauge fill, 780x48 (2026-09-15 gemless MapleStory-M
            // rebuild - replaces the previous 1665x213 ornate asset, generated
            // by build_ui_kit.py's build_mana_fill: same flat slim capsule as
            // HealthBarFrameGold's fill cell, hue-rotated blue). Used with
            // Image.Type.Filled (not Sliced), so no border/9-slice data is
            // needed - only Single import mode with alphaIsTransparency,
            // matching this file's other single-sprite calls.
            ArtImportConfigurator.ConfigureSingleSprite(
                SapphireSceneBuilder.UiArtDir + "/GaugeFillMana.png",
                border: Vector4.zero,
                filterMode: FilterMode.Bilinear,
                mipmaps: false,
                pixelsPerUnit: ArtImportConfigurator.UiKitV3PixelsPerUnit);
        }

        private static void ConfigureMovementStick()
        {
            // UI: bottom-left virtual movement pad, 792x480, 2 cells - a large
            // base ring (left, native x=[0,480]) and a smaller knob (right,
            // native x=[600,792], 120px empty gutter between) (2026-09-15
            // gemless MapleStory-M rebuild - replaces the previous 1438x902
            // asset, generated by build_ui_kit.py's build_movement_stick:
            // base_d=160/knob_d=64/gutter=40 TARGET px * SCALE(3) native). Both
            // are Image.Type.Simple with preserveAspect (no 9-slice needed),
            // so spritePixelsPerUnit has no effect on-screen - kept at the
            // shared UiKitV3PixelsPerUnit for consistency.
            //
            // Re-measured with PIL against the actual cell boundaries (native
            // x=480 divides the base cell from the knob cell, not the naive
            // canvas-half split an earlier draft of this measurement used and
            // which clipped the base ring in half): base ring bbox
            // x=[6,474] y=[6,474] (468x468, a near-perfect circle, matching
            // the generator's own radius formula to within 1px); knob bbox
            // x=[606,787] y=[150,331] (181x181), inside the full-height image.
            var centerPivot = new Vector2(0.5f, 0.5f);
            ArtImportConfigurator.ConfigureMultiSprite(
                SapphireSceneBuilder.UiArtDir + "/MovementStickGold.png",
                ppu: ArtImportConfigurator.UiKitV3PixelsPerUnit,
                filterMode: FilterMode.Bilinear,
                mipmaps: false,
                maxSize: null,
                slices: new[]
                {
                    ("MovementStickGold_Base", new Rect(6, 6, 468, 468), centerPivot),
                    ("MovementStickGold_Knob", new Rect(606, 149, 181, 181), centerPivot),
                });
        }

        private static void ConfigureMenuPanelOdin()
        {
            // UI: Odin-style right-side menu panel background, 1200x3000
            // portrait (2026-09-15 gemless MapleStory-M rebuild - replaces the
            // previous 793x1983 gold-corner asset, generated by
            // build_ui_kit.py's build_menu_panel_odin: same double-line beige
            // panel family as MessagePanelFrameGold/CharacterSlotFrame, just a
            // different target canvas size). Border re-measured with PIL
            // (inward scan): settles at 32px on all 4 edges, same value as the
            // other two members of this asset family (same generator function,
            // same margin/radius/line-width tokens - only overall size
            // differs, and the double-line decoration thickness is
            // size-invariant).
            //
            // This panel is anchored (1,0)-(1,1) and vertically STRETCHED (see
            // VillageHubMenuBuilder.Build) with a fixed width of 400 -
            // pixelsPerUnit is the shared UiKitV3PixelsPerUnit (300) rather
            // than a per-call-site nativeWidth/400 formula, since every v3
            // asset's native/target ratio is the same fixed SCALE=3 factor
            // regardless of on-screen call-site size (see that constant's doc
            // comment in ArtImportConfigurator).
            ArtImportConfigurator.ConfigureSingleSprite(
                SapphireSceneBuilder.UiArtDir + "/MenuPanelOdin.png",
                border: new Vector4(32, 32, 32, 32),
                filterMode: FilterMode.Bilinear,
                mipmaps: false,
                pixelsPerUnit: ArtImportConfigurator.UiKitV3PixelsPerUnit);
        }

        // 2026-09-15 (gemless MapleStory-M rebuild): MenuSectionHeader.png (the
        // old ornate gold banner, used both for Odin-menu section headers and
        // the top-center region name banner) is retired - both call sites
        // switch to plainer, non-gem replacements: VillageHubMenuBuilder's
        // section headers now use MenuSectionDivider.png (fading line + dot on
        // either side of the title, no banner backdrop at all - see
        // ConfigureMenuSectionDivider below), and VillageHubUiBuilder's region
        // name banner now uses the new dedicated RegionNameplate.png (see
        // ConfigureRegionNameplate below). Old asset + .meta removed via git rm
        // once both call sites were confirmed switched over (grep for zero
        // remaining references).
        private static void ConfigureMenuSectionDivider()
        {
            // UI: section-header divider, 1200x60, 2 equal cells side by side
            // (build_ui_kit.py's build_menu_section_divider: target_cell_w=200,
            // target_strip_h=20, * SCALE(3) native = 600x60 per cell - an exact
            // generator-parameter match, no measurement ambiguity). Left cell
            // fades in from the outer edge and ends in a small dot near the
            // panel's center gap; right cell mirrors it. Both
            // Image.Type.Simple (no 9-slice - a fading line can't be
            // meaningfully stretched without breaking the fade), used flanking
            // a centered section-title Text (see
            // VillageHubMenuBuilder.BuildOdinSectionHeader).
            var centerPivot = new Vector2(0.5f, 0.5f);
            ArtImportConfigurator.ConfigureMultiSprite(
                SapphireSceneBuilder.UiArtDir + "/MenuSectionDivider.png",
                ppu: ArtImportConfigurator.UiKitV3PixelsPerUnit,
                filterMode: FilterMode.Bilinear,
                mipmaps: false,
                maxSize: null,
                slices: new[]
                {
                    ("MenuSectionDivider_Left", new Rect(0, 0, 600, 60), centerPivot),
                    ("MenuSectionDivider_Right", new Rect(600, 0, 600, 60), centerPivot),
                });
        }

        private static void ConfigureRegionNameplate()
        {
            // UI: top-center region name banner, 540x96 (build_ui_kit.py's
            // build_region_nameplate: left_zone=50/mid=106/right_zone=24 TARGET
            // px * SCALE(3) native = 540 wide, target_h=32*3=96 tall). A dark
            // translucent capsule (not beige - REGION_FILL is near-black at
            // 60% alpha) with a map-pin icon already baked into its left zone
            // (native x~[51,99], well inside the border below) - no separate
            // pin sprite/icon needed at the call site.
            //
            // Border: left=152 (covers the full pin + left round cap with a
            // small buffer, so the pin is never stretched regardless of banner
            // width - PIL column-height scan confirms the cap's own curvature
            // finishes by x~40, but the pin graphic itself needs the wider
            // margin), right=54 (plain round cap only, no icon there),
            // top=0/bottom=0 (a pill's non-cap flat top/bottom edges are
            // already straight for the full stretchable middle - only the two
            // end caps have curvature, which is exactly what left/right
            // border protects).
            ArtImportConfigurator.ConfigureSingleSprite(
                SapphireSceneBuilder.UiArtDir + "/RegionNameplate.png",
                border: new Vector4(152, 0, 54, 0),
                filterMode: FilterMode.Bilinear,
                mipmaps: false,
                pixelsPerUnit: ArtImportConfigurator.UiKitV3PixelsPerUnit);
        }

        // UI: hex-cut (octagon-corner) pill buttons, 1032x456 each, 2 cells
        // stacked vertically - normal state (native rows 0-168) and a pressed
        // state (native rows 288-456, 120px empty gutter between)
        // (build_ui_kit.py's build_hex_button: target_w=344/target_h=56/
        // gutter=40 TARGET px * SCALE(3) native). ButtonSecondary (cool gray)
        // replaces MenuButtonGold for the "캐릭터 선택으로" back/footer
        // buttons; ButtonPrimary (warm brown) replaces it for the
        // 로그인/생성 screens' main action buttons (시작하기/생성) - see
        // LoginSceneBuilder/CharacterCreateSceneBuilder/VillageHubMenuBuilder
        // call sites. Border: the octagon corner cut is BTN_CUT_RATIO(0.30) *
        // target_h(56) = 16.8 target px = 50.4 native px on every corner (PIL
        // column/row profile at the top-left corner confirms this exactly -
        // e.g. at native x=40 the alpha transition sits at y~10, matching
        // 50.4-40=10.4) - 53px border (>50.4 with a small AA buffer) on all 4
        // sides keeps every corner cut fully inside the fixed, non-stretched
        // 9-slice region.
        private static void ConfigureButtons()
        {
            ConfigureHexButton("ButtonSecondary.png");
            ConfigureHexButton("ButtonPrimary.png");
        }

        private static void ConfigureHexButton(string fileName)
        {
            var centerPivot = new Vector2(0.5f, 0.5f);
            string path = SapphireSceneBuilder.UiArtDir + "/" + fileName;
            const string normalName = "Normal";
            const string pressedName = "Pressed";
            ArtImportConfigurator.ConfigureMultiSprite(
                path,
                ppu: ArtImportConfigurator.UiKitV3PixelsPerUnit,
                filterMode: FilterMode.Bilinear,
                mipmaps: false,
                maxSize: null,
                slices: new[]
                {
                    (normalName, new Rect(0, 288, 1032, 168), centerPivot),
                    (pressedName, new Rect(0, 0, 1032, 168), centerPivot),
                });

            var border = new Vector4(53, 53, 53, 53);
            ArtImportConfigurator.ApplySingleSliceBorder(path, normalName, border);
            ArtImportConfigurator.ApplySingleSliceBorder(path, pressedName, border);
        }

        private static void ConfigureMenuHamburgerIcon()
        {
            // UI: top-right menu-open icon, 240x216 - three plain white lines
            // + a soft drop shadow, NO background plate (2026-09-15, replaces
            // MenuButtonGold as the "메뉴" button's visual - the button is now
            // the icon alone, no pill backdrop, per spec "배경 없음"). The
            // 20px transparent padding baked around the icon (alpha bbox
            // [56,73]-[185,148] inside the 240x216 canvas) exists to give the
            // shadow blur room, so it's imported as a single full-canvas
            // sprite (not cropped) with Image.Type.Simple + preserveAspect at
            // the call site, matching the shadow's own margin.
            ArtImportConfigurator.ConfigureSingleSprite(
                SapphireSceneBuilder.UiArtDir + "/MenuHamburgerIcon.png",
                border: Vector4.zero,
                filterMode: FilterMode.Bilinear,
                mipmaps: false,
                pixelsPerUnit: ArtImportConfigurator.UiKitV3PixelsPerUnit);
        }

        private static void ConfigureLevelBadge()
        {
            // UI: level-number hex badge background, 192x192 (2026-09-15) -
            // sits behind the "Lv.1" text (see VillageHubUiBuilder.
            // BuildLevelText). Full-canvas single sprite, Image.Type.Simple +
            // preserveAspect at the call site (a flat-top hexagon has no
            // stretchable interior worth 9-slicing at this small a size).
            ArtImportConfigurator.ConfigureSingleSprite(
                SapphireSceneBuilder.UiArtDir + "/LevelBadgeHex.png",
                border: Vector4.zero,
                filterMode: FilterMode.Bilinear,
                mipmaps: false,
                pixelsPerUnit: ArtImportConfigurator.UiKitV3PixelsPerUnit);
        }

        // ApplySingleSliceBorder moved to ArtImportConfigurator (2026-09-16) -
        // CharacterFlowArtImportConfigurator's new button sheets need it too.
        private static void ConfigureMenuIconsSet()
        {
            // UI: menu grid icons, 1774x887, 4x2 grid (row1: equipment/bag/
            // quest/settings, row2: skillbook/character-info/map/dungeon - per
            // asset naming handed off with this file, and visually confirmed).
            // Column/row boundaries measured via the zero-alpha-count gap
            // convention (never assume an even 4x2 split) - zero-alpha column
            // runs at x=[0,29] (left margin), [414,481], [849,887], [1330,1354],
            // [1750,1773] (right margin) give 3 internal gap midpoints (447.5,
            // 868, 1342); the single zero-alpha row run at y=[420,446] gives the
            // row split midpoint (433). Every icon's own alpha content bbox was
            // checked and each sits within ~1-2% of its cell's geometric center
            // (well under half a canvas pixel at the 56px on-screen icon size
            // this sheet is used at - see VillageHubMenuBuilder), so no
            // per-icon pivot offset beyond the default center is needed.
            var centerPivot = new Vector2(0.5f, 0.5f);
            ArtImportConfigurator.ConfigureMultiSprite(
                SapphireSceneBuilder.UiArtDir + "/MenuIconsSet.png",
                ppu: 100,
                filterMode: FilterMode.Bilinear,
                mipmaps: false,
                maxSize: null,
                slices: new[]
                {
                    ("MenuIcons_Equipment", new Rect(0f, 454f, 447.5f, 433f), centerPivot),
                    ("MenuIcons_Bag", new Rect(447.5f, 454f, 420.5f, 433f), centerPivot),
                    ("MenuIcons_Quest", new Rect(868f, 454f, 474f, 433f), centerPivot),
                    ("MenuIcons_Settings", new Rect(1342f, 454f, 432f, 433f), centerPivot),
                    ("MenuIcons_SkillBook", new Rect(0f, 0f, 447.5f, 454f), centerPivot),
                    ("MenuIcons_CharacterInfo", new Rect(447.5f, 0f, 420.5f, 454f), centerPivot),
                    ("MenuIcons_Map", new Rect(868f, 0f, 474f, 454f), centerPivot),
                    ("MenuIcons_Dungeon", new Rect(1342f, 0f, 432f, 454f), centerPivot),
                });
        }

        private static void ConfigureDarkMenuArt()
        {
            ArtImportConfigurator.ConfigureSingleSprite(SapphireSceneBuilder.UiArtDir + "/MenuPanelDark.png", new Vector4(52, 52, 52, 52), FilterMode.Bilinear, false, 100f);
            var center = new Vector2(.5f, .5f);
            var names = new[] { "MenuIcons_CharacterInfo", "MenuIcons_SkillBook", "MenuIcons_Bag", "MenuIcons_Quest", "MenuIcons_Crafting", "MenuIcons_Market", "MenuIcons_Achievements", "MenuIcons_Ranking", "MenuIcons_Guild", "MenuIcons_Dungeon", "MenuIcons_Pvp", "MenuIcons_Friends", "MenuIcons_Mail", "MenuIcons_Settings", "MenuIcons_Collection", "MenuIcons_Codex", "MenuIcons_Equipment", "MenuIcons_Map", "MenuIcons_Party", "MenuIcons_Shop" };
            var slices = new (string, Rect, Vector2)[20];
            for (int i = 0; i < names.Length; i++)
                slices[i] = (names[i], new Rect((i % 5) * 280.4f, (3 - i / 5) * 280.5f, 280.4f, 280.5f), center);
            ArtImportConfigurator.ConfigureMultiSprite(SapphireSceneBuilder.UiArtDir + "/MenuIconsSetDark.png", 100, FilterMode.Bilinear, false, null, slices);
        }

        private static void ConfigureMenuLockBadge()
        {
            // UI: single padlock icon, 1278x1230 canvas, overlaid on a locked
            // menu item's icon at 40% of the icon's own size (see
            // VillageHubMenuBuilder.BuildOdinMenuItem). Tightly cropped to its
            // own alpha bbox (PIL: x=[239,1038] y=[50,1178], i.e. 799x1128, an
            // upright padlock silhouette) via SpriteImportMode.Multiple with a
            // single slice, same tight-crop convention as MenuSectionHeader
            // above, instead of importing the padded 1278x1230 canvas as a
            // Single sprite and relying on preserveAspect to hide the margin
            // (preserveAspect would still leave the padlock visually smaller
            // than the requested 40% box, since it centers within the
            // requested box scaled to the SPRITE's full, padded aspect ratio).
            ArtImportConfigurator.ConfigureMultiSprite(
                SapphireSceneBuilder.UiArtDir + "/MenuLockBadge.png",
                ppu: 100,
                filterMode: FilterMode.Bilinear,
                mipmaps: false,
                maxSize: null,
                slices: new[]
                {
                    ("MenuLockBadge", new Rect(239, 52, 799, 1128), new Vector2(0.5f, 0.5f)),
                });
        }
    }
}
