using System;
using System.Collections;
using System.IO;
using UnityEngine;
using UnityEngine.EventSystems;
using UnityEngine.UI;

namespace Lighthaven2D
{
    public sealed class FrontFlowScreen : MonoBehaviour
    {
        public Texture2D town, background, mageIdle, magePortrait, goblin, skillSheet, menuIconSheet, menuPanelTexture, hudControlSheet, uiChromeSheet, wideButtonTexture;
        public Font uiFont;
        public Texture2D[] mageAttackPoses;
        Canvas canvas; Font font; Image backdrop, townHero; GameObject content; Sprite wideButtonSprite; Sprite[] chromeSprites; int step; float townX=560;

        void Awake(){font=uiFont?uiFont:Resources.GetBuiltinResource<Font>("LegacyRuntime.ttf");wideButtonSprite=TrimmedCenter(wideButtonTexture);chromeSprites=SliceTrimmed(uiChromeSheet,4,2);Build();ShowLogin();if(Array.Exists(Environment.GetCommandLineArgs(),x=>x=="--battle-smoke"))StartCoroutine(BattleSmoke());else if(Array.Exists(Environment.GetCommandLineArgs(),x=>x=="--front-smoke"))StartCoroutine(FrontSmoke());}
        void Build(){var root=new GameObject("Front Flow",typeof(Canvas),typeof(CanvasScaler),typeof(GraphicRaycaster));canvas=root.GetComponent<Canvas>();canvas.renderMode=RenderMode.ScreenSpaceOverlay;var s=root.GetComponent<CanvasScaler>();s.uiScaleMode=CanvasScaler.ScaleMode.ScaleWithScreenSize;s.referenceResolution=new Vector2(1280,720);if(!FindAnyObjectByType<EventSystem>())new GameObject("EventSystem",typeof(EventSystem),typeof(StandaloneInputModule));backdrop=Image("Backdrop",root.transform,Sprite.Create(town,new Rect(0,0,town.width,town.height),new Vector2(.5f,.5f),100),new Vector2(640,360),new Vector2(1280,720),new Color(.42f,.48f,.58f,1),false);content=new GameObject("Content",typeof(RectTransform));content.transform.SetParent(root.transform,false);var rt=content.GetComponent<RectTransform>();rt.anchorMin=Vector2.zero;rt.anchorMax=Vector2.one;rt.offsetMin=rt.offsetMax=Vector2.zero;}
        void Clear(){for(int i=content.transform.childCount-1;i>=0;i--)Destroy(content.transform.GetChild(i).gameObject);townHero=null;}
        void ShowLogin(){step=0;Clear();Dim(.48f);Text("Title","LIGHTHAVEN",new Vector2(640,520),new Vector2(600,70),44,new Color(.78f,.9f,1));Text("Subtitle","달빛 아래 시작되는 모험",new Vector2(640,462),new Vector2(500,40),20,Color.white);Button("게스트로 시작",new Vector2(640,270),new Vector2(300,58),ShowServer);Text("Stub","온라인 계정 연동 전 로컬 로그인",new Vector2(640,220),new Vector2(360,24),14,new Color(.75f,.78f,.82f));}
        void ShowServer(){step=1;Clear();Dim(.4f);Text("Title","서버 선택",new Vector2(640,560),new Vector2(400,60),36,Color.white);Button("루나 1   원활",new Vector2(640,380),new Vector2(360,64),ShowCharacters);Button("루나 2   준비 중",new Vector2(640,300),new Vector2(360,58),null);Button("루나 3   준비 중",new Vector2(640,230),new Vector2(360,58),null);}
        void ShowCharacters(){step=2;Clear();Dim(.35f);Text("Title","캐릭터 선택",new Vector2(640,600),new Vector2(420,60),36,Color.white);var card=Panel("Mage Card",new Vector2(640,365),new Vector2(300,360),new Color(.02f,.03f,.05f,.72f));var p=Image("Portrait",card.transform,Sprite.Create(magePortrait,new Rect(0,0,magePortrait.width,magePortrait.height),new Vector2(.5f,.5f),100),new Vector2(0,40),new Vector2(230,230),Color.white,false);p.preserveAspect=true;Text("Mage Name","사파이어 메이지  ·  LV.1",new Vector2(640,250),new Vector2(300,32),20,Color.white);Button("이 캐릭터로 시작",new Vector2(640,145),new Vector2(300,58),ShowTown);}
        void ShowTown(){step=3;Clear();backdrop.color=Color.white;Text("Town","사파이어 광장",new Vector2(640,680),new Vector2(280,38),24,new Color(.92f,.94f,1));townHero=Image("Town Mage",content.transform,Trimmed(mageIdle),new Vector2(townX,315),new Vector2(170,170),Color.white,false);townHero.preserveAspect=true;Button("달빛 회랑 출정",new Vector2(1120,90),new Vector2(220,54),EnterBattle);Text("Guide","A / D 이동   ·   우측 포털에서 출정",new Vector2(640,35),new Vector2(400,28),16,Color.white);}
        void Update(){if(step!=3||!townHero)return;float x=Input.GetAxisRaw("Horizontal");townX=Mathf.Clamp(townX+x*180*Time.deltaTime,90,1190);townHero.rectTransform.anchoredPosition=new Vector2(townX,315);if(Input.GetKeyDown(KeyCode.Return)&&townX>1050)EnterBattle();}
        IEnumerator FrontSmoke(){string dir=Path.GetFullPath(Path.Combine(Application.dataPath,"../../captures/front-flow"));Directory.CreateDirectory(dir);yield return new WaitForEndOfFrame();ScreenCapture.CaptureScreenshot(Path.Combine(dir,"01-login.png"));yield return new WaitForSeconds(.35f);ShowServer();yield return new WaitForEndOfFrame();ScreenCapture.CaptureScreenshot(Path.Combine(dir,"02-server.png"));yield return new WaitForSeconds(.35f);ShowCharacters();yield return new WaitForEndOfFrame();ScreenCapture.CaptureScreenshot(Path.Combine(dir,"03-character.png"));yield return new WaitForSeconds(.35f);ShowTown();yield return new WaitForEndOfFrame();ScreenCapture.CaptureScreenshot(Path.Combine(dir,"04-town.png"));yield return new WaitForSeconds(.5f);Application.Quit(0);}
        IEnumerator BattleSmoke(){yield return new WaitForEndOfFrame();EnterBattle();}
        void EnterBattle(){var old=canvas.gameObject;var host=new GameObject("Battle Screen");host.SetActive(false);var b=host.AddComponent<BattleScreen>();b.background=background;b.mageIdle=mageIdle;b.magePortrait=magePortrait;b.goblin=goblin;b.skillSheet=skillSheet;b.menuIconSheet=menuIconSheet;b.menuPanelTexture=menuPanelTexture;b.hudControlSheet=hudControlSheet;b.uiChromeSheet=uiChromeSheet;b.uiFont=uiFont;b.mageAttackPoses=mageAttackPoses;host.SetActive(true);Destroy(old);Destroy(gameObject);}
        void Dim(float a){Image("Dim",content.transform,null,new Vector2(640,360),new Vector2(1280,720),new Color(0,0,.02f,a),false);}
        Image Panel(string n,Vector2 p,Vector2 z,Color c)=>Image(n,content.transform,chromeSprites[2],p,z,new Color(1,1,1,.72f),false);
        void Button(string label,Vector2 p,Vector2 z,UnityEngine.Events.UnityAction action){var i=Image(label,content.transform,wideButtonSprite,p,z,new Color(1,1,1,action!=null ? .92f : .5f),action!=null);i.preserveAspect=false;Text(label+" Text",label,Vector2.zero,z-new Vector2(36,12),18,action!=null?Color.white:new Color(.62f,.65f,.68f),i.transform);if(action!=null){var b=i.GetComponent<Button>();var colors=b.colors;colors.normalColor=Color.white;colors.highlightedColor=new Color(.82f,.94f,1,1);colors.pressedColor=new Color(.48f,.72f,.9f,1);colors.colorMultiplier=1;b.colors=colors;b.onClick.AddListener(()=>StartCoroutine(Transition(action)));}}
        IEnumerator Transition(UnityEngine.Events.UnityAction next){var veil=Image("Transition Veil",canvas.transform,null,new Vector2(640,360),new Vector2(1280,720),Color.clear,false);veil.transform.SetAsLastSibling();float age=0;while(age<.16f){age+=Time.unscaledDeltaTime;veil.color=new Color(0,0,.02f,Mathf.Clamp01(age/.16f)*.55f);yield return null;}next();veil.transform.SetAsLastSibling();age=0;while(age<.2f){age+=Time.unscaledDeltaTime;veil.color=new Color(0,0,.02f,(1-Mathf.Clamp01(age/.2f))*.55f);yield return null;}Destroy(veil.gameObject);}
        Text Text(string n,string v,Vector2 p,Vector2 z,int fs,Color c,Transform parent=null){var go=new GameObject(n,typeof(RectTransform),typeof(CanvasRenderer),typeof(Text));go.transform.SetParent(parent?parent:content.transform,false);var t=go.GetComponent<Text>();t.font=font;t.text=v;t.fontSize=fs;t.color=c;t.alignment=TextAnchor.MiddleCenter;t.raycastTarget=false;t.lineSpacing=1.05f;t.horizontalOverflow=HorizontalWrapMode.Overflow;t.verticalOverflow=VerticalWrapMode.Overflow;var shadow=go.AddComponent<Shadow>();shadow.effectColor=new Color(0,0,0,.65f);shadow.effectDistance=new Vector2(1,-1);var r=t.rectTransform;r.anchorMin=r.anchorMax=parent?new Vector2(.5f,.5f):Vector2.zero;r.anchoredPosition=p;r.sizeDelta=z;return t;}
        Image Image(string n,Transform parent,Sprite sp,Vector2 p,Vector2 z,Color c,bool button){var go=new GameObject(n,typeof(RectTransform),typeof(CanvasRenderer),typeof(Image));go.transform.SetParent(parent,false);var i=go.GetComponent<Image>();i.sprite=sp;i.color=c;i.raycastTarget=button;var r=i.rectTransform;r.anchorMin=r.anchorMax=parent==canvas.transform||parent==content.transform?Vector2.zero:new Vector2(.5f,.5f);r.anchoredPosition=p;r.sizeDelta=z;if(button)go.AddComponent<Button>();return i;}
        static Sprite Trimmed(Texture2D t){var p=t.GetPixels32();int a=t.width,b=t.height,c=-1,d=-1;for(int y=0;y<t.height;y++)for(int x=0;x<t.width;x++)if(p[y*t.width+x].a>8){a=Mathf.Min(a,x);b=Mathf.Min(b,y);c=Mathf.Max(c,x);d=Mathf.Max(d,y);}return Sprite.Create(t,new Rect(a,b,c-a+1,d-b+1),new Vector2(.5f,0),100);}
        static Sprite TrimmedCenter(Texture2D t){var p=t.GetPixels32();int a=t.width,b=t.height,c=-1,d=-1;for(int y=0;y<t.height;y++)for(int x=0;x<t.width;x++)if(p[y*t.width+x].a>8){a=Mathf.Min(a,x);b=Mathf.Min(b,y);c=Mathf.Max(c,x);d=Mathf.Max(d,y);}return Sprite.Create(t,new Rect(a,b,c-a+1,d-b+1),new Vector2(.5f,.5f),100);}
        static Sprite[] SliceTrimmed(Texture2D t,int columns,int rows){var result=new Sprite[columns*rows];int w=t.width/columns,h=t.height/rows;var pixels=t.GetPixels32();for(int y=0;y<rows;y++)for(int x=0;x<columns;x++){int x0=x*w,y0=y*h,minX=x0+w,minY=y0+h,maxX=-1,maxY=-1;for(int py=y0;py<y0+h;py++)for(int px=x0;px<x0+w;px++)if(pixels[py*t.width+px].a>8){minX=Mathf.Min(minX,px);minY=Mathf.Min(minY,py);maxX=Mathf.Max(maxX,px);maxY=Mathf.Max(maxY,py);}var rect=maxX<minX?new Rect(x0,y0,w,h):new Rect(minX,minY,maxX-minX+1,maxY-minY+1);result[(rows-1-y)*columns+x]=Sprite.Create(t,rect,new Vector2(.5f,.5f),100);}return result;}
    }
}
